// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgRoebvmHOWJGgaY_HGhYGLumyQ3wijo',
    appId: '1:338590444680:web:3d45079c2c7f3c2444c33d',
    messagingSenderId: '338590444680',
    projectId: 'sklps-app',
    authDomain: 'sklps-app.firebaseapp.com',
    storageBucket: 'sklps-app.appspot.com',
    measurementId: 'G-CGEBX24MBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjj8FSAMwNGxa1P3oc24p-2v6pzzbGIg',
    appId: '1:338590444680:android:2a39088a9b9407e444c33d',
    messagingSenderId: '338590444680',
    projectId: 'sklps-app',
    storageBucket: 'sklps-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJSD0wUC2YslxTv7Gc-eGc6LWS6GLtz-c',
    appId: '1:338590444680:ios:24b1cf6f6277bb2c44c33d',
    messagingSenderId: '338590444680',
    projectId: 'sklps-app',
    storageBucket: 'sklps-app.appspot.com',
    iosClientId: '338590444680-gvg29cde95e5kv2atdd6ijhqgj6ut8ps.apps.googleusercontent.com',
    iosBundleId: 'com.sklpsusa.sklpsApp2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJSD0wUC2YslxTv7Gc-eGc6LWS6GLtz-c',
    appId: '1:338590444680:ios:98b10c56e372c15344c33d',
    messagingSenderId: '338590444680',
    projectId: 'sklps-app',
    storageBucket: 'sklps-app.appspot.com',
    iosClientId: '338590444680-go78opi1gq97r4i0nvjihqmml983qglq.apps.googleusercontent.com',
    iosBundleId: 'com.sklpsusa.sklpsApp.RunnerTests',
  );
}
